<?php

namespace Database\Seeders;

use App\Models\Division;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // for ($i=15; $i <=27 ; $i++) { 
        //     DB::table('divisions')->where('id',$i + 1)->update(['id'=>$i]);
        // }
        // DB::table('divisions')->update(['created_at'=>Carbon::now()]);
        // $division = \App\Models\Division::create([
        //     'name' => 'Legal',
        //     'approver_id' => 21,
        // ]);
        // $division = \App\Models\Division::create([
        //     'name' => 'POGS',
        //     'approver_id' => 21,
        // ]);
        // $division = \App\Models\Division::create([
        //     'name' => 'C',
        //     'approver_id' => 0,
        // ]);
        // $user = \App\Models\User::create([
        //     'id' => 0,
        //     'division_id' => 0,
        //     'nik' => 000000,
        //     'name' => "BOOKING SYSTEM ADMIN",
        //     'role' => 'Admin',
        //     'email' => 'bsysadmin@doku.com',
        //     'password' => Hash::make('admin12#'),
        //     'phone' => '00000000',
        // ]);
        // $priv1 = \App\Models\ReservationPrivilege::create([
        //     'user_id' => $user->id,
        //     'zone_id' => 1,
        // ]);
        // $priv2 = \App\Models\ReservationPrivilege::create([
        //     'user_id' => $user->id,
        //     'zone_id' => 2,
        // ]);
        $users = array(
            // CC APPROVER
            // [ 'division_id' => 4, 'nik' => '13160306', 'name' => 'Victor Ramli Kwan', 'email' => 'victorkwan@doku.com', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '000000', 'hot_desk' => false, 'meeting_room' => true, ],
            // [ 'division_id' => 5, 'nik' => '13111202', 'name' => 'Irfan Imran Burhan', 'email' => 'irfan@doku.com', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '000000', 'hot_desk' => false, 'meeting_room' => true, ],
            // [ 'division_id' => 6, 'nik' => '13200107', 'name' => 'Dody Jumaidy Wijaya', 'email' => 'dodywijaya@doku.com', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '81234567890', 'hot_desk' => false, 'meeting_room' => true, ],
            // [ 'division_id' => 7, 'nik' => '13160801', 'name' => 'Swandawati Tjia', 'email' => 'swandawati@doku.com', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '81234567890', 'hot_desk' => true, 'meeting_room' => true, ],
            // [ 'division_id' => 8, 'nik' => '13210902', 'name' => 'Herunata Joseph', 'email' => 'herunata.joseph@doku.com', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '000000', 'hot_desk' => false, 'meeting_room' => true, ],
            // [ 'division_id' => 8, 'nik' => '13211105', 'name' => 'Monika Viany Ratri Rahayu', 'email' => 'monika.viany@doku.com', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '000000', 'hot_desk' => false, 'meeting_room' => true, ],
            // [ 'division_id' => 11, 'nik' => '13120902', 'name' => 'Anistasya Kristina', 'email' => 'kristin@doku.com', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '000000', 'hot_desk' => false, 'meeting_room' => true, ],
            // [ 'division_id' => 12, 'nik' => '13160701', 'name' => 'Jenny Chowi', 'email' => 'jenny.chowi@doku.com', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '000000', 'hot_desk' => false, 'meeting_room' => true, ],
            // [ 'division_id' => 20, 'nik' => '13190803', 'name' => 'Ayu Sawitri Hapsari', 'email' => '', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '000000', 'hot_desk' => false, 'meeting_room' => true, ],
            // [ 'division_id' => 21, 'nik' => '13070701', 'name' => 'Sugiharto', 'email' => 'sugiharto@doku.com', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '000000', 'hot_desk' => false, 'meeting_room' => true, ],
            // [ 'division_id' => 23, 'nik' => '13110103', 'name' => 'Nova Sjafitri Hasnil Purtanti', 'email' => 'nova@doku.com', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '000000', 'hot_desk' => false, 'meeting_room' => true, ],
            // [ 'division_id' => 23, 'nik' => '13120717', 'name' => 'Dewi Monicha Githa Friana Putri', 'email' => 'dewimonicha.githa@doku.com', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '000000', 'hot_desk' => false, 'meeting_room' => true, ],
            // [ 'division_id' => 23, 'nik' => '13170302', 'name' => 'Trisna Kumala', 'email' => 'trisna@doku.com', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '000000', 'hot_desk' => false, 'meeting_room' => true, ],
            // [ 'division_id' => 23, 'nik' => '13171102', 'name' => 'Palti Raja Siregar', 'email' => 'palti.siregar@doku.com', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '000000', 'hot_desk' => false, 'meeting_room' => true, ],
            // [ 'division_id' => 23, 'nik' => '13180503', 'name' => 'Kartika Aprillina Ningrum', 'email' => 'kartika@doku.com', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '000000', 'hot_desk' => false, 'meeting_room' => true, ],
            // [ 'division_id' => 23, 'nik' => '13200104', 'name' => 'Nuri Fatmala Zaman', 'email' => 'nuri@doku.com', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '000000', 'hot_desk' => false, 'meeting_room' => true, ],
            // [ 'division_id' => 23, 'nik' => '13210203', 'name' => 'Arlita Widyastuti', 'email' => 'arlita.widyastuti@doku.com', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '000000', 'hot_desk' => false, 'meeting_room' => true, ],
            // [ 'division_id' => 23, 'nik' => '13220101', 'name' => 'Dyah Bayurini', 'email' => 'Dyah Bayurini', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '000000', 'hot_desk' => false, 'meeting_room' => true, ],
            // [ 'division_id' => 1, 'nik' => '13080201', 'name' => 'Hafiz', 'email' => 'hafiz@doku.com', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '000000', 'hot_desk' => false, 'meeting_room' => true, ],
            // [ 'division_id' => , 'nik' => '', 'name' => '', 'email' => '', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '000000', 'hot_desk' => false, 'meeting_room' => true, ],
            // [ 'division_id' => 2, 'nik' => '13040301', 'name' => 'Rama Prahara', 'email' => 'rama@doku.com', 'role' => 'Head Officer', 'approver_id' => null, 'cc_id' => null, 'phone' => '000000', 'hot_desk' => false, 'meeting_room' => true, ],
            //TL DEV 1, TL DEV 2, REISA, TL SUPP1, TL SUPP2
            // [ 'division_id' => 1, 'nik' => '1000005', 'name' => 'TL DEV 1', 'email' => 'TLDEV1@doku.com', 'role' => 'TL', 'approver_id' => 2, 'cc_id' => null, 'phone' => '81234567890', 'hot_desk' => true, 'meeting_room' => true, ], [ 'division_id' => 1, 'nik' => '1000006', 'name' => 'TL DEV 2', 'email' => 'TLDEV2@doku.com', 'role' => 'TL', 'approver_id' => 2, 'cc_id' => null, 'phone' => '81234567890', 'hot_desk' => true, 'meeting_room' => true, ], [ 'division_id' => 1, 'nik' => '1000019', 'name' => 'Rnoor', 'role' => 'TL', 'approver_id' => 2, 'cc_id' => null, 'phone' => '81234567890', 'hot_desk' => true, 'meeting_room' => true, ], 
            // [ 'division_id' => 1, 'nik' => '1000010', 'email' => 'reisa@doku.com', 'name' => 'REISA', 'role' => 'TL', 'approver_id' => 3, 'cc_id' => null, 'phone' => '81234567890', 'hot_desk' => true, 'meeting_room' => true, ], [ 'division_id' => 1, 'nik' => '1000019', 'name' => 'Rnoor', 'role' => 'TL', 'approver_id' => 2, 'cc_id' => null, 'phone' => '81234567890', 'hot_desk' => true, 'meeting_room' => true, ], 
            // [ 'division_id' => 1, 'nik' => '1000015', 'name' => 'TL SUPP 1', 'email' => 'TLSUPP1@doku.com', 'role' => 'TL', 'approver_id' => 4, 'cc_id' => null, 'phone' => '81234567890', 'hot_desk' => true, 'meeting_room' => true, ], [ 'division_id' => 1, 'nik' => '1000019', 'name' => 'Rnoor', 'role' => 'TL', 'approver_id' => 2, 'cc_id' => null, 'phone' => '81234567890', 'hot_desk' => true, 'meeting_room' => true, ], 
            // [ 'division_id' => 1, 'nik' => '1000016', 'name' => 'TL SUPP 2', 'email' => 'TLSUPP2@doku.com', 'role' => 'TL', 'approver_id' => 4, 'cc_id' => null, 'phone' => '81234567890', 'hot_desk' => true, 'meeting_room' => true, ], [ 'division_id' => 1, 'nik' => '1000019', 'name' => 'Rnoor', 'role' => 'TL', 'approver_id' => 2, 'cc_id' => null, 'phone' => '81234567890', 'hot_desk' => true, 'meeting_room' => true, ],
            //mamah nakal
            //  [ 'division_id' => 5, 'nik' => '1000032', 'name' => 'CTK', 'email' => 'ctk@doku.com', 'role' => 'TL', 'approver_id' => null, 'cc_id' => null, 'phone' => '81234567890', 'hot_desk' => true, 'meeting_room' => true, ], 
            //  [ 'division_id' => 5, 'nik' => '1000028', 'name' => 'NOVA', 'email' => 'nova@doku.com', 'role' => 'TL', 'approver_id' => 21, 'cc_id' => null, 'phone' => '81234567890', 'hot_desk' => true, 'meeting_room' => true, ], 
            //  [ 'division_id' => 5, 'nik' => '1000029', 'name' => 'PALTI', 'email' => 'palti@doku.com', 'role' => 'TL', 'approver_id' => 22, 'cc_id' => 21, 'phone' => '81234567890', 'hot_desk' => true, 'meeting_room' => true, ], 
            //  [ 'division_id' => 5, 'nik' => '1000030', 'name' => 'TONO', 'email' => 'tono@doku.com', 'role' => 'TL', 'approver_id' => 22, 'cc_id' => 21, 'phone' => '81234567890', 'hot_desk' => true, 'meeting_room' => true, ], 
            //  [ 'division_id' => 5, 'nik' => '1000030', 'name' => 'RASNO', 'email' => 'rasno@doku.com', 'role' => 'TL', 'approver_id' => 23, 'cc_id' => 22, 'phone' => '81234567890', 'hot_desk' => true, 'meeting_room' => true, ], 
            //  [ 'division_id' => 5, 'nik' => '1000033', 'name' => 'GITHA', 'email' => 'githa@doku.com', 'role' => 'TL', 'approver_id' => 21, 'cc_id' => null, 'phone' => '81234567890', 'hot_desk' => true, 'meeting_room' => true, ], 
            //  [ 'division_id' => 5, 'nik' => '1000034', 'name' => 'YUAN', 'email' => 'yuan@doku.com', 'role' => 'TL', 'approver_id' => 27, 'cc_id' => 21, 'phone' => '81234567890', 'hot_desk' => false, 'meeting_room' => true, ], 
            //  [ 'division_id' => 5, 'nik' => '1000034', 'name' => 'YUAN', 'email' => 'yuan@doku.com', 'role' => 'TL', 'approver_id' => 27, 'cc_id' => 21, 'phone' => '81234567890', 'hot_desk' => false, 'meeting_room' => true, ], 
            
        );
        //dev  1-4
        // for ($i=1; $i <= 4; $i++) { 
        //     array_push($users,[ 'division_id' => 1, 'nik' => '100000'.$i, 'name' => 'DEV '.$i, 'email' => 'DEV'.$i.'@doku.com', 'role' => 'STAFF', 'approver_id' => ($i <= 2 ? 5 : 6), 'cc_id' => 2, 'phone' => '81234567890', 'hot_desk' => true, 'meeting_room' => true, ]); 
        // }
        //infra 1-3
        // for ($i=1; $i <= 3; $i++) { 
        //     array_push($users,[ 'division_id' => 1, 'nik' => '100000'.$i+6, 'name' => 'INFRA '.$i, 'email' => 'INFRA'.$i.'@doku.com', 'role' => 'STAFF', 'approver_id' =>7, 'cc_id' => 3, 'phone' => '81234567890', 'hot_desk' => true, 'meeting_room' => true, ]); 
        // }
        //supp  1-4
        // for ($i=1; $i <= 4; $i++) { 
        //     array_push($users,[ 'division_id' => 1, 'nik' => '100000'.$i+10, 'name' => 'SUPP '.$i, 'email' => 'SUPP '.$i.'@doku.com', 'role' => 'STAFF', 'approver_id' => ($i <= 2 ? 5 : 6), 'cc_id' => 2, 'phone' => '81234567890', 'hot_desk' => true, 'meeting_room' => true, ]); 
        // }
        $users = array(
        //     0 => array('nik' => '13070501', 'role' => 'Head Officer', 'phone' => '000000', 'name' => 'Himelda Renuat', 'email' => 'melda@doku.com', 'division_id' => '26', 'approver_id' => null, 'cc_id' => null, 'hot_desk' => false, 'meeting_room' => true),
        //     1 => array('nik' => '13211207', 'role' => 'Head Officer', 'phone' => '000000', 'name' => 'Venkata Ravi Rama Krishna Gupta Kancharla', 'email' => 'gupta@doku.com', 'division_id' => '26', 'approver_id' => null, 'cc_id' => null, 'hot_desk' => false, 'meeting_room' => true),
        //     2 => array('nik' => '13181120', 'role' => 'Head Officer', 'phone' => '000000', 'name' => 'Richmond Aldien', 'email' => 'ricky@doku.com', 'division_id' => '26', 'approver_id' => null, 'cc_id' => null, 'hot_desk' => false, 'meeting_room' => true),
        //     3 => array('nik' => '13190407', 'role' => 'Head Officer', 'phone' => '000000', 'name' => 'Benedictus Rama Aditya', 'email' => 'benedictus.aditya@doku.com', 'division_id' => '26', 'approver_id' => null, 'cc_id' => null, 'hot_desk' => false, 'meeting_room' => true),
        //     4 => array('nik' => '13090701', 'role' => 'Head Officer', 'phone' => '000000', 'name' => 'Mohamad Triana Walujadjati', 'email' => 'djati@doku.com', 'division_id' => '3', 'approver_id' => null, 'cc_id' => null, 'hot_desk' => false, 'meeting_room' => true),
        //     5 => array('nik' => '13131003', 'role' => 'Head Officer', 'phone' => '000000', 'name' => 'Alison Jap', 'email' => 'alison@doku.com', 'division_id' => '26', 'approver_id' => null, 'cc_id' => null, 'hot_desk' => false, 'meeting_room' => true),
        //     6 => array('nik' => '13070502', 'role' => 'Head Officer', 'phone' => '000000', 'name' => 'Nabilah Alsagoff', 'email' => 'nabilah@doku.com', 'division_id' => '26', 'approver_id' => null, 'cc_id' => null, 'hot_desk' => false, 'meeting_room' => true),
        // [ "nik" => 13110801, "name" => "Tengku Abdullah Zaki", "email" => "zaki@doku.com", "division_id" => 6, "approver_id" => 5, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, 'role' => 'TL', "phone" => 0], [ "nik" => 13150803, "name" => "Retna Mahesti Indrarini", "email" => "retna@doku.com", "division_id" => 7, "approver_id" => 6, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, 'role' => 'TL', "phone" => 0], [ "nik" => 13190704, "name" => "Bony Ary Seto", "email" => "bony@doku.com", "division_id" => 2, "approver_id" => 25, "cc_id" => null, "hot_desk" => true, "meeting_room" => true, 'role' => 'TL', "phone" => 0], [ "nik" => 13160802, "name" => "Herianto ", "email" => "heri.marbun@doku.com", "division_id" => 13, "approver_id" => 25, "cc_id" => null, "hot_desk" => true, "meeting_room" => true, 'role' => 'TL', "phone" => 0], [ "nik" => 13211204, "name" => "Jeremiah Kevin Dennis Jacob", "email" => "jeremiah.kevin@doku.com", "division_id" => 14, "approver_id" => 29, "cc_id" => null, "hot_desk" => false, 'role' => 'TL', "meeting_room" => true, "phone" => 0], [ "nik" => 13210601, "name" => "Khaira Al Hafi", "email" => "khaira.hafi@doku.com", "division_id" => 15, "approver_id" => 25, "cc_id" => null, "hot_desk" => true, "meeting_room" => true, 'role' => 'TL', "phone" => 0], [ "nik" => 13080601, "name" => "Roky Huisman", "email" => "roky@doku.com", "division_id" => 18, "approver_id" => 30, "cc_id" => null, "hot_desk" => true, "meeting_room" => true, 'role' => 'TL', "phone" => 0], [ "nik" => 13101101, "name" => "M. Riza Abdillah", "email" => "riza@doku.com", "division_id" => 21, "approver_id" => 25, "cc_id" => null, "hot_desk" => true, "meeting_room" => true, 'role' => 'TL', "phone" => 0]
            // [ 'division_id' => 9, 'nik' => '13200311', 'name' => 'Rachma Fitria Kandini', 'email' => 'rachma.fitria@doku.com', 'role' => 'TL', 'approver_id' => 37, 'cc_id' => null, 'phone' => '0000', 'hot_desk' => true, 'meeting_room' => true, ], [ 'division_id' => 1, 'nik' => '1000019', 'name' => 'Rnoor', 'role' => 'TL', 'approver_id' => 2, 'cc_id' => null, 'phone' => '81234567890', 'hot_desk' => true, 'meeting_room' => true, ],
            // ["nik" => 13110301,"name" => "Dhian Yuni", "email" => "dhian@doku.com","division_id" => 4,"approver_id" => 33,"cc_id" => 3,"hot_desk" => false,"meeting_room" => true,"phone" => 0, 'role'=>'STAFF'],
            // ["nik" => 13130110,"name" => "Doddy Iriawan", "email" => "doddy.iriawan@doku.com","division_id" => 4,"approver_id" => 33,"cc_id" => 3,"hot_desk" => false,"meeting_room" => true,"phone" => 0, 'role'=>'STAFF'],
            // ["nik" => 13170501,"name" => "Mirfahmi Rahman", "email" => "mirfahmi.rahman@doku.com","division_id" => 4,"approver_id" => 33,"cc_id" => 3,"hot_desk" => false,"meeting_room" => true,"phone" => 0, 'role'=>'STAFF'],
            // ["nik" => 13180904,"name" => "Deblin Tanudjaja", "email" => "deblin@doku.com","division_id" => 4,"approver_id" => 33,"cc_id" => 3,"hot_desk" => false,"meeting_room" => true,"phone" => 0, 'role'=>'STAFF'],
            // ["nik" => 13190904,"name" => "Julitha Putri","email" => "julitha@doku.com","division_id" => 4,"approver_id" => 46,"cc_id" => 3,"hot_desk" => "FALSE","meeting_room" => "TRUE","phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210501,"name" => "Sophia Claudia S. Tulenan","email" => "sophia.claudia@doku.com","division_id" => 4,"approver_id" => 46,"cc_id" => 3,"hot_desk" => "FALSE","meeting_room" => "TRUE","phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13211205,"name" => "Helda Chintia","email" => "helda.chintia@doku.com","division_id" => 4,"approver_id" => 47,"cc_id" => 3,"hot_desk" => "FALSE","meeting_room" => "TRUE","phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13181208,"name" => "Aryo Panji N","email" => "aryo.panji@doku.com","division_id" => 5,"approver_id" => 34,"cc_id" => 4,"hot_desk" => "FALSE","meeting_room" => "TRUE","phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210402,"name" => "Ni Komang Ary Pratiwi","email" => "komang.ary@doku.com","division_id" => 5,"approver_id" => 4,"cc_id" => 4,"hot_desk" => "FALSE","meeting_room" => "TRUE","phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13140102,"name" => "Dimas Haditya Yoga","email" => "dimas.haditya@doku.com","division_id" => 6,"approver_id" => 35,"cc_id" => 5,"hot_desk" => "FALSE","meeting_room" => "TRUE","phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13170104,"name" => "Elfany Dwijayanti","email" => "elfany@doku.com","division_id" => 6,"approver_id" => 35,"cc_id" => 5,"hot_desk" => "FALSE","meeting_room" => "TRUE","phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200305,"name" => "Victor Daniel","email" => "victor.daniel@doku.com","division_id" => 6,"approver_id" => 35,"cc_id" => 5,"hot_desk" => "FALSE","meeting_room" => "TRUE","phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200310,"name" => "Cherry Capriciani","email" => "cherry@doku.com","division_id" => 6,"approver_id" => 35,"cc_id" => 5,"hot_desk" => "FALSE","meeting_room" => "TRUE","phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200602,"name" => "Selly Mercylina","email" => "selly@doku.com","division_id" => 6,"approver_id" => 35,"cc_id" => 5,"hot_desk" => "FALSE","meeting_room" => "TRUE","phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13211203,"name" => "Clarissa Jelita Putri","email" => "clarissa.putri@doku.com","division_id" => 6,"approver_id" => 35,"cc_id" => 5,"hot_desk" => "FALSE","meeting_room" => "TRUE","phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13160803,"name" => "Nurul Ulfa","email" => "nurul.ulfa@doku.com","division_id" => 7,"approver_id" => 36,"cc_id" => 6,"hot_desk" => "FALSE","meeting_room" => "TRUE","phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13170303,"name" => "Meilandi ","email" => "meilandi@doku.com","division_id" => 7,"approver_id" => 36,"cc_id" => 6,"hot_desk" => "FALSE","meeting_room" => "TRUE","phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190405,"name" => "Asep Septiadi Nugraha","email" => "asep.septiadi@doku.com","division_id" => 7,"approver_id" => 36,"cc_id" => 6,"hot_desk" => "FALSE","meeting_room" => "TRUE","phone" => 0, "role" => "STAFF"],
	        // ["nik" => 13111002,"name" => "Widi Prihatna","email" => "widi.prihatna@doku.com","division_id" => 9,"approver_id" => 43,"cc_id" => 37,"hot_desk" => "FALSE","meeting_room" => "TRUE","phone" => 0, "role" => "STAFF"],
            // ["nik" => 13170805, "name" => "Farida Rentua", "email" => "farida@doku.com", "division_id" => 5, "approver_id" => 51, "cc_id" => 4, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13191201, "name" => "Rimaputi Febriyanti", "email" => "rimaputi@doku.com", "division_id" => 5, "approver_id" => 51, "cc_id" => 4, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210306, "name" => "Donovan Typhano Rachmadie", "email" => "donovan.typhano@doku.com", "division_id" => 5, "approver_id" => 51, "cc_id" => 4, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210502, "name" => "Theresa Novita Iyandraputri", "email" => "theresa.novita@doku.com", "division_id" => 5, "approver_id" => 51, "cc_id" => 4, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210703, "name" => "Nico Abiawan", "email" => "nico.abiawan@doku.com", "division_id" => 5, "approver_id" => 51, "cc_id" => 4, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13180101, "name" => "Naufalia Andita", "email" => "naufalia.andita@doku.com", "division_id" => 9, "approver_id" => 62, "cc_id" => 37, "hot_desk" => true, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200403, "name" => "Rizki Ade Putra", "email" => "rizki.ade@doku.com", "division_id" => 9, "approver_id" => 43, "cc_id" => 37, "hot_desk" => true, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200909, "name" => "Achmad Rizal Irsyadi", "email" => "achmad.rizal@doku.com", "division_id" => 9, "approver_id" => 43, "cc_id" => 37, "hot_desk" => true, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210401, "name" => "Gerry Zogy Hasiholan", "email" => "gerry.zogy@doku.com", "division_id" => 9, "approver_id" => 43, "cc_id" => 37, "hot_desk" => true, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210407, "name" => "Anggouldy Frizman", "email" => "anggouldy.frizman@doku.com", "division_id" => 9, "approver_id" => 37, "cc_id" => null, "hot_desk" => true, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200307, "name" => "Made Wendy Wirawan", "email" => "wendy@doku.com", "division_id" => 10, "approver_id" => 28, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13170204, "name" => "Rr Fannie Waldhani Christinari", "email" => "fannie.waldhani@doku.com", "division_id" => 11, "approver_id" => 9, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13211009, "name" => "Tashya  Ballerina Agatha", "email" => "tashya.ballerina@doku.com", "division_id" => 11, "approver_id" => 9, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190207, "name" => "Azizah Nur Hanifah", "email" => "azizah@doku.com", "division_id" => 12, "approver_id" => 10, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210702, "name" => "Bilqis Fani Zulfakanti", "email" => "bilqis.fani@doku.com", "division_id" => 12, "approver_id" => 10, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13211104, "name" => "Annissa Gabianti Anggriana", "email" => "annissa.gabianti@doku.com", "division_id" => 12, "approver_id" => 10, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13080801, "name" => "Reza Farasdak", "email" => "rezafarasdak@doku.com", "division_id" => 2, "approver_id" => 37, "cc_id" => null, "hot_desk" => true, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13110802, "name" => "Mohammad Surya Saputra", "email" => "surya@doku.com", "division_id" => 2, "approver_id" => 37, "cc_id" => null, "hot_desk" => true, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190705, "name" => "Dwina Febria", "email" => "dwina@doku.com", "division_id" => 2, "approver_id" => 37, "cc_id" => null, "hot_desk" => true, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200309, "name" => "Sagaf Ibn Umar Assagaff", "email" => "sagaf@doku.com", "division_id" => 2, "approver_id" => 37, "cc_id" => null, "hot_desk" => true, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200603, "name" => "Yani Mandasari", "email" => "yani@doku.com", "division_id" => 2, "approver_id" => 37, "cc_id" => null, "hot_desk" => true, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210204, "name" => "Anton Faturahman Latief", "email" => "anton.faturahman@doku.com", "division_id" => 2, "approver_id" => 37, "cc_id" => null, "hot_desk" => true, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190906, "name" => "Ria Florensi Azhar", "email" => "ria.florensi@doku.com", "division_id" => 13, "approver_id" => 38, "cc_id" => null, "hot_desk" => true, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13211002, "name" => "Brithy Michelle Toar", "email" => "brithy.michelle@doku.com", "division_id" => 13, "approver_id" => 38, "cc_id" => null, "hot_desk" => true, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13180203, "name" => "I Gusti Ayu Putu Maharani", "email" => "ayu.putu@doku.com", "division_id" => 14, "approver_id" => 29, "cc_id" => 39, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13180501, "name" => "Enda ", "email" => "enda@doku.com", "division_id" => 14, "approver_id" => 29, "cc_id" => 39, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13180907, "name" => "Andi Setyo Mayarso", "email" => "andisetyo@doku.com", "division_id" => 14, "approver_id" => 29, "cc_id" => 39, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "STAFF"],
            // ["nik" => 13080101,"name" => "Sobinoto Tambunan","email" => "sby_tbn@doku.com","division_id" => 14,"approver_id" => 89,"cc_id" => 39,"hot_desk" => false,"meeting_room" => true,"phone" => 0,"role" => "TL"], 
            // ["nik" => 13130703,"name" => "Irene Silvia Napitupulu","email" => "irene@doku.com","division_id" => 14,"approver_id" => 90,"cc_id" => 39,"hot_desk" => false,"meeting_room" => true,"phone" => 0,"role" => "TL"], 
            // ["nik" => 13180401,"name" => "Harsono ","email" => "harsono@doku.com","division_id" => 14,"approver_id" => 89,"cc_id" => 39,"hot_desk" => false,"meeting_room" => true,"phone" => 0,"role" => "TL"], 
            // ["nik" => 13191203,"name" => "Yoga Setyawan","email" => "yoga.setyawan@doku.com","division_id" => 14,"approver_id" => 90,"cc_id" => 39,"hot_desk" => false,"meeting_room" => true,"phone" => 0,"role" => "TL"], 
            // ["nik" => 13200908,"name" => "Ganda Kharisma Hendra","email" => "michael.ganda@doku.com","division_id" => 16,"approver_id" => 31,"cc_id" => null,"hot_desk" => false,"meeting_room" => true,"phone" => 0,"role" => "TL"], 
            // ["nik" => 13110701,"name" => "Gyandhi Yogaperdana","email" => "gyoga@doku.com","division_id" => 18,"approver_id" => 41,"cc_id" => null,"hot_desk" => true,"meeting_room" => true,"phone" => 0,"role" => "TL"], 
            // ["nik" => 13121002,"name" => "Reisa Arif Kharismiawan","email" => "reisa.arif@doku.com","division_id" => 18,"approver_id" => 41,"cc_id" => null,"hot_desk" => true,"meeting_room" => true,"phone" => 0,"role" => "TL"], 
            // ["nik" => 13200304,"name" => "Bagas Purwohandoyo","email" => "bagas@doku.com","division_id" => 18,"approver_id" => 41,"cc_id" => null,"hot_desk" => true,"meeting_room" => true,"phone" => 0,"role" => "TL"], 
            // ["nik" => 13110902,"name" => "Henry Saudale","email" => "henrysaudale@doku.com","division_id" => 19,"approver_id" => 11,"cc_id" => null,"hot_desk" => false,"meeting_room" => true,"phone" => 0,"role" => "TL"], 
            // ["nik" => 13170106,"name" => "Alfa Hanita Sinta Kusuma","email" => "sinta.kusuma@doku.com","division_id" => 19,"approver_id" => 11,"cc_id" => null,"hot_desk" => false,"meeting_room" => true,"phone" => 0,"role" => "TL"], 
            // ["nik" => 13170201,"name" => "Stenaldo Abdinegara Kabut","email" => "stenaldo@doku.com","division_id" => 19,"approver_id" => 11,"cc_id" => null,"hot_desk" => false,"meeting_room" => true,"phone" => 0,"role" => "TL"], 
            // ["nik" => 13190905,"name" => "Susan Handajani Jogadinata","email" => "susanjo@doku.com","division_id" => 20,"approver_id" => 12,"cc_id" => null,"hot_desk" => false,"meeting_room" => true,"phone" => 0,"role" => "TL"],
            // ["nik" => 13080102, "name" => "Chairul Saleh", "email" => "arul@doku.com", "division_id" => 17, "approver_id" => 100, "cc_id" => 41, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13100101, "name" => "Diki Hijratullah", "email" => "diki.hijratullah@doku.com", "division_id" => 20, "approver_id" => 105, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13151002, "name" => "Suharno ", "email" => "suharno@doku.com", "division_id" => 20, "approver_id" => 105, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13180801, "name" => "Dery Mukti Hardiansah", "email" => "derymukti@doku.com", "division_id" => 20, "approver_id" => 105, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13090101, "name" => "Taufik Ismail", "email" => "taufik@doku.com", "division_id" => 21, "approver_id" => "42", "cc_id" => null, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"],
            // ["nik" => 13100901, "name" => "Fatha Firdaus", "email" => "fatha.firdaus@doku.com", "division_id" => 20, "approver_id" => 107, "cc_id" => 12, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13101002, "name" => "Andry Pohan", "email" => "andrypohan@doku.com", "division_id" => 20, "approver_id" => 108, "cc_id" => 12, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13101004, "name" => "Wahidin ", "email" => "wahidin@doku.com", "division_id" => 20, "approver_id" => 107, "cc_id" => 12, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13111102, "name" => "Agustian Suhendar", "email" => "tian@doku.com", "division_id" => 20, "approver_id" => 109, "cc_id" => 12, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13121003, "name" => "Gatot Budi Perkasa", "email" => "gatot.budiperkasa@doku.com", "division_id" => 20, "approver_id" => 107, "cc_id" => 12, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13191206, "name" => "Yola Septiana Saputri", "email" => "yolaseptiana@doku.com", "division_id" => 22, "approver_id" => 18, "cc_id" => 13, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13191002, "name" => "Christina Eka Wardani", "email" => "dina@doku.com", "division_id" => 23, "approver_id" => 24, "cc_id" => null, "hot_desk" => true, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13180109, "name" => "Rizqi Noor Husaga", "email" => "rizqi.noor@doku.com", "division_id" => 25, "approver_id" => 30, "cc_id" => null, "hot_desk" => true, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13110601, "name" => "Andi Yanata Sanit", "email" => "nata@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13130104, "name" => "Faisal Hadi", "email" => "faisal.hadi@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13140603, "name" => "Mohammad Iqbal Saleh", "email" => "iqbal@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13140902, "name" => "Rendi Hari Kusuma", "email" => "rendi@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13150404, "name" => "Surahma Jaya", "email" => "rahma.jaya@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13160202, "name" => "Muhammad Okfriansyah", "email" => "okfriansyah@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13160307, "name" => "Dinar Firdaus", "email" => "dinar@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13160501, "name" => "Adhi Wicaksono", "email" => "adhiwicaksono@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13170904, "name" => "Rafi Devandra Yusmananda", "email" => "rafi.devandra@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13180703, "name" => "Abel Hidayat", "email" => "abel@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13181106, "name" => "Mirza Dita Ardani", "email" => "mirza@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13181112, "name" => "Stefanus Dear Damanik", "email" => "stefanus@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13190305, "name" => "Laurence ", "email" => "laurence@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13190908, "name" => "Ridwan Wulida Siam", "email" => "ridwan.siam@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13200103, "name" => "Nurmalita Sari", "email" => "nurmalita@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13200401, "name" => "Akida Tawaka", "email" => "akida@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"], 
            // ["nik" => 13200904, "name" => "Oky Suryadi", "email" => "oky.suryadi@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"],
            // ["nik" => 13100801, "name" => "Aulia Alnifal", "email" => "aulia.alnifal@doku.com", "division_id" => 20, "approver_id" => 107, "cc_id" => 12, "hot_desk" => false, "meeting_room" => true, "phone" => 0, "role" => "TL"],
            // ["nik" => 13111201, "name" => "Saldi Antonio", "email" => "saldi@doku.com", "division_id" => 20, "approver_id" => 115, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "TL"], 
            // ["nik" => 13120903, "name" => "Marwandi ", "email" => "marwandi@doku.com", "division_id" => 20, "approver_id" => 115, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "TL"], 
            // ["nik" => 13121104, "name" => "Rinto Gorlimsah Pasaribu", "email" => "rinto@doku.com", "division_id" => 20, "approver_id" => 115, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "TL"], 
            // ["nik" => 13150302, "name" => "Yus Suhendra", "email" => "yus.suhendra@doku.com", "division_id" => 20, "approver_id" => 115, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "TL"], 
            // ["nik" => 13160203, "name" => "Tommy Trihastomo", "email" => "tommy@doku.com", "division_id" => 20, "approver_id" => 115, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "TL"], 
            // ["nik" => 13160804, "name" => "Yansen Marsim", "email" => "yansen-care@doku.com", "division_id" => 20, "approver_id" => 109, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "TL"], 
            // ["nik" => 13180802, "name" => "Leni Zakia Romdania", "email" => "leni@doku.com", "division_id" => 20, "approver_id" => 109, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "TL"], 
            // ["nik" => 13180918, "name" => "Farid Ali Mukti", "email" => "farid@doku.com", "division_id" => 20, "approver_id" => 109, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "TL"], 
            // ["nik" => 13130202, "name" => "Sarjoko ", "email" => "sarjoko@doku.com", "division_id" => 25, "approver_id" => 119, "cc_id" => 119, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "TL"], 
            // ["nik" => 13150705, "name" => "Andi Kusbiantoro", "email" => "andi.kusbiantoro@doku.com", "division_id" => 25, "approver_id" => 119, "cc_id" => null, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "TL"], 
            // ["nik" => 13180903, "name" => "Arrijal Hanif", "email" => "arrijal@doku.com", "division_id" => 25, "approver_id" => 119, "cc_id" => null, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "TL"], 
            // ["nik" => 13110402, "name" => "Muhammad Rahdiansyah", "email" => "rahdian@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "TL"], 
            // ["nik" => 13130801, "name" => "Arif Bahtiar Rifai", "email" => "arif@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "TL"], 
            // ["nik" => 13170603, "name" => "Rudi Hartono", "email" => "rudi.hartono@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "TL"], 
            // ["nik" => 13180705, "name" => "Haryosonirbito Waharyogo", "email" => "haryoso@doku.com", "division_id" => 1, "approver_id" => 122, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "TL"], 
            // ["nik" => 13181002, "name" => "Asido Christian Panjaitan", "email" => "asido@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "TL"], 
            // ["nik" => 13181202, "name" => "Muhammad Zulfikri Khair", "email" => "zulfikri@doku.com", "division_id" => 1, "approver_id" => 122, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "TL"],
            // ["nik" => 13130606, "name" => "Siti Rochmah", "email" => "rochmah@doku.com", "division_id" => 14, "approver_id" => 90, "cc_id" => 39, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13141203, "name" => "Yeti Rohayati", "email" => "yeti.rohayati@doku.com", "division_id" => 14, "approver_id" => 95, "cc_id" => 39, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13150702, "name" => "Della Farleta", "email" => "della@doku.com", "division_id" => 14, "approver_id" => 88, "cc_id" => 39, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13170802, "name" => "Ryan Steven", "email" => "ryan@doku.com", "division_id" => 14, "approver_id" => 94, "cc_id" => 39, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13180110, "name" => "Danti Rahmawati", "email" => "danti.rahmawati@doku.com", "division_id" => 14, "approver_id" => 97, "cc_id" => 39, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13181104, "name" => "Rifqi Muhammad Lionar", "email" => "rifqi@doku.com", "division_id" => 14, "approver_id" => 96, "cc_id" => 39, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190206, "name" => "Zainal Abidin", "email" => "zainal.abidin@doku.com", "division_id" => 14, "approver_id" => 97, "cc_id" => 39, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13191102, "name" => "Yuliana ", "email" => "yuliana@doku.com", "division_id" => 14, "approver_id" => 96, "cc_id" => 39, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13191103, "name" => "Muhammad Fadillah", "email" => "m.fadillah@doku.com", "division_id" => 14, "approver_id" => 96, "cc_id" => 39, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13201102, "name" => "Fury Oktria Putra", "email" => "fury@doku.com", "division_id" => 15, "approver_id" => 40, "cc_id" => null, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13211005, "name" => "Ricky Hilmi Sudrajad", "email" => "ricky.hilmi@doku.com", "division_id" => 15, "approver_id" => 40, "cc_id" => null, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13170801, "name" => "Marsya Ramadia Asikin", "email" => "marsya@doku.com", "division_id" => 16, "approver_id" => 31, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210904, "name" => "Krishna Susanto", "email" => "krishna.susanto@doku.com", "division_id" => 16, "approver_id" => 98, "cc_id" => 31, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210905, "name" => "Amala Kristovia Kurniawan", "email" => "amala.kristovia@doku.com", "division_id" => 16, "approver_id" => 98, "cc_id" => 31, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13160903, "name" => "Candra Napitupulu", "email" => "candra@doku.com", "division_id" => 18, "approver_id" => 99, "cc_id" => 41, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13171101, "name" => "Muhammad Dimas Arfianto", "email" => "dimas.arfianto@doku.com", "division_id" => 18, "approver_id" => 100, "cc_id" => 41, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13180108, "name" => "Dewangga Arie Baskara", "email" => "dewangga@doku.com", "division_id" => 17, "approver_id" => 106, "cc_id" => 41, "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200303, "name" => "Salsa Dian Sikahita", "email" => "salsa@doku.com", "division_id" => 18, "approver_id" => 100, "cc_id" => 41, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13211206, "name" => "Dhanny Gamola", "email" => "dhanny.gamola@doku.com", "division_id" => 18, "approver_id" => 100, "cc_id" => 41, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13180504, "name" => "Purwoko Pramana E", "email" => "pramana@doku.com", "division_id" => 19, "approver_id" => 104, "cc_id" => 11, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190501, "name" => "Harry Kurniawan", "email" => "harry@doku.com", "division_id" => 19, "approver_id" => 102, "cc_id" => 11, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190702, "name" => "Rainer Tangdililing", "email" => "rainer@doku.com", "division_id" => 19, "approver_id" => 104, "cc_id" => 11, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200208, "name" => "Mentari Nur Amalia Putri", "email" => "mentari@doku.com", "division_id" => 19, "approver_id" => 104, "cc_id" => 11, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210602, "name" => "Theodora Paramita Pratiwi", "email" => "theodora@doku.com", "division_id" => 19, "approver_id" => 103, "cc_id" => 11, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13211102, "name" => "Dina Arristy", "email" => "dina.arristy@doku.com", "division_id" => 19, "approver_id" => 102, "cc_id" => 11, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13100102, "name" => "Eko Kurniadi", "email" => "eko.kurniadi@doku.com", "division_id" => 20, "approver_id" => 107, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13101003, "name" => "Rierin Kurniawaty Ano", "email" => "rierin.kurniawaty@doku.com", "division_id" => 20, "approver_id" => 112, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13101006, "name" => "Cahya Irawan", "email" => "cahya.irawan@doku.com", "division_id" => 20, "approver_id" => 114, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13101102, "name" => "Rully Alberto Budibasana", "email" => "rully.alberto@doku.com", "division_id" => 20, "approver_id" => 116, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13101103, "name" => "Kemas Muhammad Firmansyah", "email" => "kemas.firmansyah@doku.com", "division_id" => 20, "approver_id" => 116, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13101204, "name" => "Irmawati ", "email" => "irmawati@doku.com", "division_id" => 20, "approver_id" => 112, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13110201, "name" => "Yetty Novita Sari H", "email" => "yetty.novitasari@doku.com", "division_id" => 20, "approver_id" => 137, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13110404, "name" => "Achmad Ansyori", "email" => "achmad.ansyori@doku.com", "division_id" => 20, "approver_id" => 114, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13110901, "name" => "Uli Tua Fk Tambunan", "email" => "uli.tua@doku.com", "division_id" => 20, "approver_id" => 137, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13120401, "name" => "Desi Purwanti", "email" => "desi@doku.com", "division_id" => 20, "approver_id" => 108, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13120905, "name" => "Marini ", "email" => "marini@doku.com", "division_id" => 20, "approver_id" => 113, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13130502, "name" => "Aris Setiawan, St", "email" => "aris@doku.com", "division_id" => 20, "approver_id" => 108, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13131002, "name" => "Bobot Adi Wahono", "email" => "bobot@doku.com", "division_id" => 20, "approver_id" => 139, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13140101, "name" => "Ria Kurniawan", "email" => "ria.kurniawan@doku.com", "division_id" => 20, "approver_id" => 108, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13160209, "name" => "Rudi Permana", "email" => "rudi.permana@doku.com", "division_id" => 20, "approver_id" => 141, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13170102, "name" => "Anggun Tri Prasetyo", "email" => "anggun@doku.com", "division_id" => 20, "approver_id" => 108, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13170205, "name" => "Yeny Amelia Amir Halimi", "email" => "yeny@doku.com", "division_id" => 20, "approver_id" => 140, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13170705, "name" => "Albert Kurniawan Djendjengi", "email" => "albert.kurniawan@doku.com", "division_id" => 20, "approver_id" => 142, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13170906, "name" => "Safia Fatma", "email" => "safia.fatma@doku.com", "division_id" => 20, "approver_id" => 113, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13171105, "name" => "Husin Munandar", "email" => "husin.munandar@doku.com", "division_id" => 20, "approver_id" => 144, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13180908, "name" => "Faiz Al Farizi", "email" => "faiz@doku.com", "division_id" => 20, "approver_id" => 138, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13180912, "name" => "Melinda Maharani", "email" => "melinda@doku.com", "division_id" => 20, "approver_id" => 139, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13180913, "name" => "Widi Setiawan", "email" => "widi.setiawan@doku.com", "division_id" => 20, "approver_id" => 141, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13180914, "name" => "Mufid Tri Subekti", "email" => "mufid@doku.com", "division_id" => 20, "approver_id" => 138, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13180915, "name" => "Sigit Prabowo", "email" => "sigit@doku.com", "division_id" => 20, "approver_id" => 140, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13180916, "name" => "Rekno Ayu Astuti", "email" => "rekno@doku.com", "division_id" => 20, "approver_id" => 141, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13180917, "name" => "Ellyn Sari Talenta Br Butar Butar", "email" => "ellyn.sari@doku.com", "division_id" => 20, "approver_id" => 145, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13180920, "name" => "Eko Sulistiawan", "email" => "eko.sulistiawan@doku.com", "division_id" => 20, "approver_id" => 143, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13181010, "name" => "Muhammad Ghifary Alif Archie", "email" => "ghifary@doku.com", "division_id" => 20, "approver_id" => 141, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13181014, "name" => "Dede Kurniawan", "email" => "dede@doku.com", "division_id" => 20, "approver_id" => 108, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13181105, "name" => "Junita Kirana Adi Saleh", "email" => "junita@doku.com", "division_id" => 20, "approver_id" => 145, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13181115, "name" => "Siti Riskayanti", "email" => "siti.riska@doku.com", "division_id" => 20, "approver_id" => 141, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13181116, "name" => "Molegia Classik Kharismatik", "email" => "molegia@doku.com", "division_id" => 20, "approver_id" => 138, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13181117, "name" => "Yolanda Amazia Putri", "email" => "yolanda@doku.com", "division_id" => 20, "approver_id" => 141, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200910, "name" => "Muthia Teja Lestari", "email" => "muthia@doku.com", "division_id" => 20, "approver_id" => 139, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210103, "name" => "Gilang Pambudi Pardiyan", "email" => "gilang.pambudi@doku.com", "division_id" => 20, "approver_id" => 140, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13211006, "name" => "Rehan Fahrobi", "email" => "rehan.fahrobi@doku.com", "division_id" => 20, "approver_id" => 142, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13211008, "name" => "Ickal Zulfikar Satria", "email" => "ickal.zulfikar@doku.com", "division_id" => 20, "approver_id" => 142, "cc_id" => 12, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200207, "name" => "Sudarto ", "email" => "sudarto@doku.com", "division_id" => 21, "approver_id" => 42, "cc_id" => null, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210102, "name" => "Jessica Tessalonika", "email" => "jessica@doku.com", "division_id" => 21, "approver_id" => 42, "cc_id" => null, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210405, "name" => "Andreas Dharmawan", "email" => "andreas.dharmawan@doku.com", "division_id" => 21, "approver_id" => 42, "cc_id" => null, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13170703, "name" => "Prant Feran Gaharu", "email" => "prant@doku.com", "division_id" => 23, "approver_id" => 118, "cc_id" => null, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13181012, "name" => "Yuri Pramana", "email" => "yuri@doku.com", "division_id" => 23, "approver_id" => 118, "cc_id" => null, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190404, "name" => "Mutiara Bela", "email" => "bela@doku.com", "division_id" => 23, "approver_id" => 118, "cc_id" => null, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190701, "name" => "Andrew Aloysius Putra Napitupulu", "email" => "andrew@doku.com", "division_id" => 23, "approver_id" => 118, "cc_id" => null, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200302, "name" => "Riski Puspa Dewi Diangga Putri", "email" => "riski.puspa@doku.com", "division_id" => 23, "approver_id" => 118, "cc_id" => null, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200802, "name" => "Farhanna ", "email" => "farhanna@doku.com", "division_id" => 23, "approver_id" => 118, "cc_id" => null, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210301, "name" => "Rindu Prasetyo", "email" => "rindu.prasetyo@doku.com", "division_id" => 23, "approver_id" => 118, "cc_id" => null, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13220102, "name" => "Sutera Darmawan", "email" => "sutera.darmawan@doku.com", "division_id" => 24, "approver_id" => 29, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13120702, "name" => "Aldy Surya Wahyudi", "email" => "aldy@doku.com", "division_id" => 25, "approver_id" => 147, "cc_id" => 119, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13121004, "name" => "Komarudin ", "email" => "komarudin@doku.com", "division_id" => 25, "approver_id" => 146, "cc_id" => 119, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13140601, "name" => "Muhammad Firzan", "email" => "firzan@doku.com", "division_id" => 25, "approver_id" => 146, "cc_id" => 119, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13150704, "name" => "Adittia ", "email" => "adittia@doku.com", "division_id" => 25, "approver_id" => 148, "cc_id" => 119, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13160603, "name" => "Ade Irwansyah", "email" => "ade.irwansyah@doku.com", "division_id" => 25, "approver_id" => 119, "cc_id" => null, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13180706, "name" => "Stanley Purwahariyanto", "email" => "stanley@doku.com", "division_id" => 25, "approver_id" => 148, "cc_id" => 119, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13181017, "name" => "Amri Danades", "email" => "amri@doku.com", "division_id" => 25, "approver_id" => 119, "cc_id" => null, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190209, "name" => "Muhammad Fahrizi", "email" => "fahrizi@doku.com", "division_id" => 25, "approver_id" => 147, "cc_id" => 119, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190703, "name" => "Ahmad Iqbal Ghazaly", "email" => "ahmad.iqbal@doku.com", "division_id" => 25, "approver_id" => 119, "cc_id" => null, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13191003, "name" => "Muhammad Faisal Akbar", "email" => "faisal@doku.com", "division_id" => 25, "approver_id" => 147, "cc_id" => 119, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210701, "name" => "Muhammad Alif Assidiq", "email" => "m.alif@doku.com", "division_id" => 25, "approver_id" => 147, "cc_id" => 119, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210801, "name" => "Mohamad Zhahir Arief Tadjoedin", "email" => "m.zhahir@doku.com", "division_id" => 25, "approver_id" => 147, "cc_id" => 119, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13211101, "name" => "Talenta  Mesianna Sitorus", "email" => "talenta.mesianna@doku.com", "division_id" => 25, "approver_id" => 148, "cc_id" => 119, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13211103, "name" => "Astin Izzah Candrawati", "email" => "astin.izzah@doku.com", "division_id" => 25, "approver_id" => 146, "cc_id" => 119, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13220106, "name" => "Rafi Fauzan Fathin", "email" => "rafi.fauzan@doku.com", "division_id" => 25, "approver_id" => 146, "cc_id" => 119, "hot_desk" => "TRUE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13110602, "name" => "Jauhaf ", "email" => "jauhaf@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13141104, "name" => "Achmad Firdaus", "email" => "ahmad.firdaus@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13141204, "name" => "Dedye Irawan", "email" => "dedye.irawan@doku.com", "division_id" => 1, "approver_id" => 130, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13170301, "name" => "Firman Hanafi", "email" => "firman.hanafi@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13170604, "name" => "Firmansyah Putra", "email" => "firmansyah.putra@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13170702, "name" => "Syahrul Fathi", "email" => "syahrul.fathi@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13171002, "name" => "Susanty Tirta", "email" => "susanty@doku.com", "division_id" => 1, "approver_id" => 154, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13180901, "name" => "Yhose Christ Widtantio", "email" => "yhosechrist@doku.com", "division_id" => 1, "approver_id" => 125, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13181004, "name" => "Sweli Giri", "email" => "sweli@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13181102, "name" => "Valentinus Silalahi", "email" => "valentinus@doku.com", "division_id" => 1, "approver_id" => 131, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13181109, "name" => "Dimas Agil Marenda", "email" => "dimas.agil@doku.com", "division_id" => 1, "approver_id" => 125, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13181110, "name" => "Andika Putra Ramadhan", "email" => "andika@doku.com", "division_id" => 1, "approver_id" => 135, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13181111, "name" => "Rizal Muhammad Ardiansyah", "email" => "rizal@doku.com", "division_id" => 1, "approver_id" => 120, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13181118, "name" => "Oscar Hutajulu", "email" => "oscar@doku.com", "division_id" => 1, "approver_id" => 126, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13181205, "name" => "Fauzan Hilmy Abyan", "email" => "fauzan@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13181206, "name" => "Grace Elvioretha Pasaribu", "email" => "grace@doku.com", "division_id" => 1, "approver_id" => 133, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190201, "name" => "Muhammad Abdul Aziz", "email" => "abdul.aziz@doku.com", "division_id" => 1, "approver_id" => 129, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190203, "name" => "Alexander Ang", "email" => "alexander@doku.com", "division_id" => 1, "approver_id" => 127, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190204, "name" => "Apriwida Yanti", "email" => "Apriwida@doku.com", "division_id" => 1, "approver_id" => 134, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190306, "name" => "Mohammad Fahmy Arsyaad", "email" => "fahmy@doku.com", "division_id" => 1, "approver_id" => 135, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190307, "name" => "Satria Adhika Pamungkas", "email" => "satria@doku.com", "division_id" => 1, "approver_id" => 120, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190309, "name" => "Jamal Fazlur Rahman", "email" => "jamal@doku.com", "division_id" => 1, "approver_id" => 121, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190310, "name" => "Muhammad Zulfikar Mey Lendra", "email" => "zulfikar@doku.com", "division_id" => 1, "approver_id" => 128, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190402, "name" => "Muhammad Fajri Azka", "email" => "fajri@doku.com", "division_id" => 1, "approver_id" => 135, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190503, "name" => "Muchlis Firmansyah", "email" => "muchlis@doku.com", "division_id" => 1, "approver_id" => 129, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190903, "name" => "Adji Pratama Permana Putra", "email" => "adji@doku.com", "division_id" => 1, "approver_id" => 128, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13190910, "name" => "Ulfa Intania Ramadhani", "email" => "ulfa@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200105, "name" => "Muhammad Rizky Pahlawan", "email" => "rizky.pahlawan@doku.com", "division_id" => 1, "approver_id" => 152, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200201, "name" => "Heryatmo Benediktus Sembiring", "email" => "hery@doku.com", "division_id" => 1, "approver_id" => 123, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200202, "name" => "Indrafani Juwasono Panjaitan", "email" => "indra@doku.com", "division_id" => 1, "approver_id" => 125, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200203, "name" => "Wenny Ty. Situmorang", "email" => "wenny@doku.com", "division_id" => 1, "approver_id" => 131, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200204, "name" => "Isnaini Nor Rahmadhani", "email" => "isna@doku.com", "division_id" => 1, "approver_id" => 120, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200205, "name" => "Diah Ajeng Dwi Yuniasih", "email" => "ajeng@doku.com", "division_id" => 1, "approver_id" => 127, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200206, "name" => "Palti Gorat Christian Sinaga", "email" => "palti.gorat@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200301, "name" => "Arvendo ", "email" => "arvendo@doku.com", "division_id" => 1, "approver_id" => 153, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200308, "name" => "Yohanes ", "email" => "yohanes@doku.com", "division_id" => 1, "approver_id" => 154, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200312, "name" => "Yoka Maulana Putra", "email" => "yoka@doku.com", "division_id" => 1, "approver_id" => 151, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200402, "name" => "Alwan Firdaus", "email" => "alwan@doku.com", "division_id" => 1, "approver_id" => 151, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200701, "name" => "Arip Hidayat", "email" => "arip@doku.com", "division_id" => 1, "approver_id" => 150, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200801, "name" => "Daniel Joi Partogi Hutapea", "email" => "daniel@doku.com", "division_id" => 1, "approver_id" => 135, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200901, "name" => "Alifiani Fauzia", "email" => "alifiani@doku.com", "division_id" => 1, "approver_id" => 150, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200902, "name" => "Agung Gumelar", "email" => "agung.gumelar@doku.com", "division_id" => 1, "approver_id" => 149, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200905, "name" => "Mega Aulia Ramadhani", "email" => "mega@doku.com", "division_id" => 1, "approver_id" => 127, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200906, "name" => "Nur Radiatun", "email" => "nur.radiatun@doku.com", "division_id" => 1, "approver_id" => 125, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200907, "name" => "Prillyandini Nurul Hidayah", "email" => "prillyandini@doku.com", "division_id" => 1, "approver_id" => 123, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200911, "name" => "Dita Puspita", "email" => "dita@doku.com", "division_id" => 1, "approver_id" => 121, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13200913, "name" => "Jasmine Nabila Novel", "email" => "jasmine@doku.com", "division_id" => 1, "approver_id" => 132, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13201001, "name" => "Kornelius Irfandhi", "email" => "kornelius.irfandhi@doku.com", "division_id" => 1, "approver_id" => 134, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13201003, "name" => "Ilham Amajidi", "email" => "ilham.amajidi@doku.com", "division_id" => 1, "approver_id" => 136, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13201101, "name" => "Dwi Wicaksono", "email" => "dwi.wicaksono@doku.com", "division_id" => 1, "approver_id" => 135, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210202, "name" => "Ristia Nadia Permata", "email" => "ristia.nadia@doku.com", "division_id" => 1, "approver_id" => 126, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210205, "name" => "Muhammad Rizki Fani", "email" => "rizki.fani@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210206, "name" => "Fahmi Oktapriansyah Lubis", "email" => "fahmi.oktapriansyah@doku.com", "division_id" => 1, "approver_id" => 131, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210302, "name" => "Lily Anastasia Naibaho", "email" => "lily.anastasia@doku.com", "division_id" => 1, "approver_id" => 130, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210303, "name" => "Luthfan Kin Gumandar", "email" => "luthfan.kin@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210404, "name" => "Gilang Widianto Aldiansyah", "email" => "gilang.widianto@doku.com", "division_id" => 1, "approver_id" => 132, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210408, "name" => "Hanif Jaka Permana", "email" => "hanif.jaka@doku.com", "division_id" => 1, "approver_id" => 129, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210503, "name" => "M. Adrian Hasan Soulisa", "email" => "adrian.soulisa@doku.com", "division_id" => 1, "approver_id" => 136, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210504, "name" => "Dwirianda Rhesa Ghani", "email" => "rhesa.ghani@doku.com", "division_id" => 1, "approver_id" => 124, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210603, "name" => "Muti Insani Siahaan", "email" => "muti.insani@doku.com", "division_id" => 1, "approver_id" => 124, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210604, "name" => "Muhammad Aufa Helfiandri", "email" => "aufa.helfiandri@doku.com", "division_id" => 1, "approver_id" => 124, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210802, "name" => "Winda Cahyaningrum", "email" => "winda.cahya@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13210903, "name" => "Rafi Mochamad Fahreza", "email" => "rafi.fahreza@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13211001, "name" => "Debby Melishawati Choirun Nisa", "email" => "debby.melishawati@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13211003, "name" => "Hartanti Saragih", "email" => "hartanti.saragih@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13211004, "name" => "Erwin Wiguna", "email" => "erwin.wiguna@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13211106, "name" => "Egi Muhamad Saeful Haqi", "email" => "egi@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13211107, "name" => "Iqbal Firmansyah", "email" => "iqbal.firmansyah@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13211201, "name" => "Ilga Anne Tri Junia Suhastuti", "email" => "ilga.suhastuti@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13211202, "name" => "Hendra Fauzi Nugraha", "email" => "hendra.fauzi@doku.com", "division_id" => 1, "approver_id" => 136, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13211208, "name" => "Wendy Pieter Manurung", "email" => "wendy.pieter@doku.com", "division_id" => 1, "approver_id" => 153, "cc_id" => 24, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"], 
            // ["nik" => 13220103, "name" => "Paulus Adiatma", "email" => "paulus.adiatma@doku.com", "division_id" => 1, "approver_id" => 24, "cc_id" => null, "hot_desk" => "FALSE", "meeting_room" => "TRUE", "phone" => 0, "role" => "STAFF"]
        );
        
        foreach ($users as $u) {
            $insert = \App\Models\User::create([
                'division_id' => $u['division_id'],
                'nik' => $u['nik'],
                'name' => $u['name'],
                'email' => $u['email'],
                'role' => $u['role'],
                'approver_id' => $u['approver_id'],
                'cc_id' => $u['cc_id'],
                'phone' => $u['phone'],
                'password' => Hash::make('Doku12#'),
            ]);
            if ($u['hot_desk']) {
                $priv = \App\Models\ReservationPrivilege::create([
                    'user_id' => $insert->id,
                    'zone_id' => 1,
                ]);
            }
            if ($u['meeting_room']) {
                $priv = \App\Models\ReservationPrivilege::create([
                    'user_id' => $insert->id,
                    'zone_id' => 2,
                ]);
            }
        }

        // for ($i=11; $i <=18 ; $i++) { 
        //     $update = \App\Models\User::find($i);
        //     $update->id = $i-2;
        //     $update->save();
        // }
    }
}
